
# Analisis descriptivo de datos

Se utiliza el `df`, ya que no tiene variables estandarizadas.

```{r}
df <- read.csv("Data/df.csv")
```


```{r}

df = df %>%
  select(where(~n_distinct(.) > 1))

```

```{r}

df <- df %>%
  janitor::clean_names()

```

```{r}

colSums(is.na(df))

```

# Estadistica descriptiva

```{r}

summary(select_if(df, is.numeric))

```

```{r}

numeric_vars = select_if(df, is.numeric)

```

```{r}

describe(numeric_vars) # Funcion del paquete psych

```

**Ciclo** `for` para visualizacion de variables numericas en un histograma

```{r}

for (var in names(numeric_vars)) {
  print(
    ggplot(df, aes(x = .data[[var]])) +
      geom_histogram(fill = "steelblue", color = "black", bins = 20, na.rm = TRUE) +
      theme_minimal() +
      labs(title = paste("Distribución de", var), x = var, y = "Frecuencia") +
      theme(plot.title = element_text(hjust = 0.5))
  )
}

```

**Despues** de analizar la variables numericas, se realizar analisis de categorica

```{r}

categorical_vars = select_if(df, is.factor)
for (var in names(categorical_vars)) {
  print(ggplot(categorical_vars, aes_string(x = var)) +
          geom_bar(fill = "orange", color = "black") +
          theme_minimal() +
          labs(title = paste("Frecuencia de", var), x = var, y = "Frecuencia") +
          theme(
            axis.text.x = element_text(angle = 45, hjust = 1),
            plot.title = element_text(hjust = 0.5)
          )
  )
}

```

### Escolaridad

```{r}

datos_escolaridad <- df %>%
  select(escolaridad)

datos_escolaridad <- datos_escolaridad %>%
  group_by(escolaridad) %>%
  summarise(conteo = n()) %>%
  mutate(porcentaje = round((conteo / sum(conteo)) * 100, 3))

ggplot(datos_escolaridad, aes(x = "", y = porcentaje, fill = escolaridad)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  labs(
    title = "Distribución de nivel de escolaridad",
    fill = "Escolaridad"   # La leyenda comienza con mayúscula
  ) +
  theme_void() +
  geom_text(
    aes(label = paste0(porcentaje, "%")),
    position = position_stack(vjust = 0.5),
    color = "black",
    size = 3
  ) +
  theme(
    plot.title = element_text(
      hjust = 3,          # Centra el título
      face = "bold",        # Negrita para título
      size = 16
    ),
    legend.title = element_text(face = "bold", size = 12),
    legend.text = element_text(size = 11)
  ) +
  scale_fill_brewer(palette = "Set2")  # Colores más formales (pasteles suaves)

```

### Variables categoricas

```{r}

datos_categoricos <- df %>%
  select(
    medicamento_psiquiatrico,
    discapacidad_fisica,
    suicidio_familiar,
    ruptura_reciente,
    crisis_pareja_actual,
    medidas_cautelares
  )

g1 <- ggplot(datos_categoricos, aes(x = medicamento_psiquiatrico)) +
  geom_bar(fill = "#1F77B4") +
  labs(title = "Uso de Medicamento Psiquiátrico", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

g2 <- ggplot(datos_categoricos, aes(x = discapacidad_fisica)) +
  geom_bar(fill = "#FF7F0E") +
  labs(title = "Discapacidad Física", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

g3 <- ggplot(datos_categoricos, aes(x = suicidio_familiar)) +
  geom_bar(fill = "#2CA02C") +
  labs(title = "Suicidio Familiar", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

g4 <- ggplot(datos_categoricos, aes(x = ruptura_reciente)) +
  geom_bar(fill = "#D62728") +
  labs(title = "Ruptura Reciente", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

g5 <- ggplot(datos_categoricos, aes(x = crisis_pareja_actual)) +
  geom_bar(fill = "#9467BD") +
  labs(title = "Crisis Pareja Actual", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

g6 <- ggplot(datos_categoricos, aes(x = medidas_cautelares)) +
  geom_bar(fill = "#7F7F7F") +
  labs(title = "Medidas Cautelares", x = NULL, y = "Frecuencia") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 8))

```

```{r}

plot_grid(g1, g2, g3, g4, g5, g6,
          ncol = 2)

```

